name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    name: Build
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        rust-toolchain:
          - stable
          - beta
    steps:
      - name: Clone
        uses: actions/checkout@v2
      - name: Cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            ~/.rustup
            target
          key: ${{ runner.os }}-${{ matrix.rust-toolchain }}
      - uses: actions-rs/toolchain@v1
        name: Set Toolchain
        with:
          toolchain: ${{ matrix.rust-toolchain }}
      - uses: actions-rs/cargo@v1
        name: Build - Full
        with:
          command: build
          args: --verbose --target=x86_64-pc-windows-gnu
          use-cross: true
      - uses: actions-rs/cargo@v1
        name: Test - Full
        with:
          command: test
          args: --verbose --target=x86_64-pc-windows-gnu
          use-cross: true
      - uses: actions-rs/cargo@v1
        name: Build - Minimal
        with:
          command: build
          args: --verbose --target=x86_64-pc-windows-gnu --features minimal --no-default-features
          use-cross: true
      - uses: actions-rs/cargo@v1
        name: Test - Minimal
        with:
          command: test
          args: --verbose --target=x86_64-pc-windows-gnu --features minimal --no-default-features
          use-cross: true