name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    name: Build
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        rust-toolchain:
          - stable
          - beta
    steps:
      - name: Clone
        uses: actions/checkout@v2
      - name: Cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            ~/.rustup
            target
          key: ${{ runner.os }}-${{ matrix.rust-toolchain }}
      - uses: actions-rs/toolchain@v1
        name: Set Toolchain
        with:
          toolchain: ${{ matrix.rust-toolchain }}
      - uses: actions-rs/cargo@v1
        name: Build
        with:
          command: build
          args: --verbose
      - uses: actions-rs/cargo@v1
        name: Test
        with:
          command: test
          args: --verbose